version: "3.7"
services:
  fetcher:
    build: docker/fetcher
    working_dir: /app
    volumes:
      - .:/app

  parser:
    build: docker/parser
    working_dir: /app
    volumes:
      - .:/app

  loader:
    build: docker/loader
    working_dir: /app
    volumes:
      - .:/app
