version: "3.7"
services:
  mysql:
    build:
      context: docker/mysql
      target: ${ENVIRONMENT:-production-pseudo}
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: usr
      MYSQL_PASSWORD: pass
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./docker/mysql/my.cnf:/root/.my.cnf

volumes:
  mysql:

networks:
  default:
    name: moyohi_database_network
    driver: bridge
