version: "3.7"
services:
  rust:
    build:
      context: docker/rust
      target: ${ENVIRONMENT:-production-pseudo}
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - default
      - database

networks:
  database:
    name: moyohi_database_network
    driver: bridge
